apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: env
  name: env
  namespace: mynamespace
spec:
  containers:
  - command:
    - sh
    - -c
    - env
    image: busybox
    name: env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
