apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - args:
    image: nginx
    name: nginx-1
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www
    ports:
    - containerPort: 80
    - containerPort: 443
  initContainers:
  - name: init-nginx
    image: busybox
    command: ["wget", "-O", "/work-dir/index.html", "http://neverssl.com/online"]
    volumeMounts:
    - mountPath: /work-dir
      name: www
  restartPolicy: Never

  volumes:
  - name: www
    emptyDir: {}