apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: hello-cron
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: hello-cron
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: hello-cron
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
