apiVersion: v1
kind: Pod
metadata:
  name: nginx-another-cm
spec:
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx
      envFrom:
      - configMapRef:
          name: anotherone
  restartPolicy: Never