apiVersion: v1
kind: Pod
metadata:
  name: nginx-cmvolume
spec:
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx
      volumeMounts:
      - name: cmvolume
        mountPath: /etc/lala
  volumes:
    - name: cmvolume
      configMap:
        name: cmvolume
  restartPolicy: Never