apiVersion: v1
kind: Pod
metadata:
  name: nginx-sec
spec:
  securityContext:
    runAsUser: 101
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]

  restartPolicy: Never